//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Controlls/controlls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controlls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controlls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""controlls"",
    ""maps"": [
        {
            ""name"": ""bullet_hell"",
            ""id"": ""f0f737fe-bb61-4e68-a002-2165ff12b565"",
            ""actions"": [
                {
                    ""name"": ""move_rigth"",
                    ""type"": ""Button"",
                    ""id"": ""bf91b95c-d35e-41fb-ba7b-fea2274f20a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""move_left"",
                    ""type"": ""Button"",
                    ""id"": ""d3695ff6-bb93-4396-89d7-566f19a688fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""move_up"",
                    ""type"": ""Button"",
                    ""id"": ""7669a425-2159-41cf-8e20-4f2179b25804"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""move_down"",
                    ""type"": ""Button"",
                    ""id"": ""05c8a075-2460-4b8e-a3cf-105675779aa6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""pause_menu"",
                    ""type"": ""Button"",
                    ""id"": ""82f0b198-e0a7-4278-8de2-262b4a9d0639"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""shoot"",
                    ""type"": ""Button"",
                    ""id"": ""0b8c52fa-a532-48cc-add5-d8fcf69b0865"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""doge"",
                    ""type"": ""Button"",
                    ""id"": ""7502b748-3d25-49d0-80e5-e54c60aa5ce0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""16afa7b9-32b8-46f0-9bbb-b8290e7611fa"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_rigth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3665340-239e-4f2a-a6bb-f5090e035dec"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_rigth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dcefa7d-ae93-4f47-af23-722c8842ba72"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e84f1ccc-534d-422d-9d71-583321b4aa1f"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75bcca6f-cb44-4c75-8b0c-69c626407f9c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6eb4bb6-d44d-4af7-982e-446ffa64739a"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91a4d8ad-ce8a-4bf8-ae46-eb3ced8da93e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c31b4e3d-2843-49c5-b59f-0dc05c10640e"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move_down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfdc6b99-6e85-4345-a466-847da6985468"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pause_menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47a3172c-2bae-41b7-bf1a-0f4d24cdec7c"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pause_menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c7ea018-fa91-40ff-a075-2ff90d8355de"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""316bdf6f-d3fa-4912-876c-5deba9c46017"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9b42444-200d-413e-8c62-d8d2374f5cac"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""doge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b836c7ef-0f52-4751-a213-471029224e9d"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""doge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""f2f4acdd-d62e-489f-b988-e9463d5a8514"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""06087f84-8f93-4282-b4a3-bd15407dde86"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""9ef21f0d-a887-46b4-9911-2152e2b15b1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""02cf0a50-8137-48cc-b6e5-5579d19ea4e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ce416132-92ec-43ff-86b4-613e1b23e69c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f152c3f5-4d9a-4355-9aca-cf2f927d3e27"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""09622b82-2aa2-4f73-bed1-ec9385134e53"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a0f4fc61-4fb1-4db5-aa8c-85be535669f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ecaf567f-c597-4f7c-aff1-361a2db3e954"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDevicePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""86970a4e-b2ee-4b10-afe0-91082843a096"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackedDeviceOrientation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ee132a24-6d45-448f-bef1-c9c3746df035"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""0d7f7437-a7d2-417d-89d0-88dd1377ea3d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d78037da-d25c-4b9c-a475-f38d8ee94472"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e5643a2d-3e8d-4ecb-9430-d4b198898ff6"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3257983e-1c87-4850-8e90-62987c245843"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""130ae5bf-03a8-4842-a9ce-c1a164e6aa81"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1a4cbb5f-ea3d-411e-8ae7-6f8e94a99845"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b48fe963-93f5-4d3a-aaf8-659a7072935b"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cd7db52d-b5d0-49f0-a3ef-c2b0ae454430"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""48856247-3c06-45a2-9d2a-003a321092df"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8e7ccd46-f0ad-4a3d-97a7-d2a29b2d2c52"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""1f858272-3e7a-4e57-867a-39f68201cc56"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f93055c2-11ff-4e92-b4b0-8c171cd04bf2"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""202194ee-dee6-4f39-9749-3cc38130f334"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4dc5062d-c55d-462b-a6dc-f31aab56f859"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4c97b83d-eedc-42a2-ab47-5671353b42d2"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""4699cb9d-6565-405e-9226-8c62f2c959ec"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9906fc61-c7ca-49f9-820f-2791e1bba161"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e4c768e0-f50c-43d3-a9ac-0e5f6faa7bc5"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""72dee3ff-2e8a-4b50-8758-ac364c245e2a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d4ff5f75-5451-4a66-835f-5a2234f019eb"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""adeaaa03-a4aa-4f1f-a875-6c15d412a2ff"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4d4c0229-161e-4fc9-8e37-4307f2948058"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4bd03e04-34be-4a7e-8fc7-6adbad1e1277"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cb91ef5a-7a22-427f-aa76-0665621bdf7f"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""818836bc-8074-4197-a48b-ab6e5572a10d"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80c726f2-bacf-4a1d-832d-bbbea98f162e"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de7d63b7-e815-4e49-bb35-e394e6392bed"",
                    ""path"": ""<VirtualMouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e98c628f-3a66-4ab4-b62b-f185993ee793"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0de5119-34d9-49d6-a25b-b380e2bb11ce"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50896b4f-801c-4736-af63-726531c76b72"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4cf30e20-7728-4d66-ba40-b40cb3161136"",
                    ""path"": ""<VirtualMouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1be55cbd-6e68-4fe1-b4ef-9b3f5035494f"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b02dd9f-fe51-4338-b223-0807849363db"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touch"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""921ae672-34f7-4a5c-9782-9566abd11afb"",
                    ""path"": ""<XRController>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52fd38c8-91b1-44a1-b0d8-941727c04384"",
                    ""path"": ""<VirtualMouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bf26276-83a8-4aa0-b0b3-a0d3f9de2e03"",
                    ""path"": ""<VirtualMouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5db1eb0-f3bb-4bbd-816b-6064c3ff72cc"",
                    ""path"": ""<VirtualMouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a6bb4ba-c578-47a6-8401-e984275d50a7"",
                    ""path"": ""<XRController>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDevicePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""198dc0fe-cc11-4e28-ba2a-c6558520f212"",
                    ""path"": ""<XRController>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""XR"",
                    ""action"": ""TrackedDeviceOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""VirtualMouse"",
            ""id"": ""52727f55-1f33-44d4-92a2-f9142d8b9f2a"",
            ""actions"": [
                {
                    ""name"": ""point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d1dd2bee-8f05-4855-a57b-9baa5c0a84a5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""moveCursor"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0ca6bfc9-1baf-4cef-8a79-efaedb03a56a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""leftMouseButton"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6fc22425-2afe-4249-ba5b-d2537b5c7508"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""rightMouseButton"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6fc952ee-00b7-4071-add2-7654010a2455"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""middleMouseButton"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ff994310-f772-4ceb-a838-8dcbe7b894f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""scroll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""23d5f862-e02e-4453-9e19-e55359e2d2b5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""toogleMouseVisibility"",
                    ""type"": ""Button"",
                    ""id"": ""34afdf12-a19f-4687-9e8f-a6167ee119fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""41c14efb-0ad1-4f81-bd7d-e8aec20b1e5f"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""daa5aac9-89ed-4a2d-b7ad-ac7a42dde095"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveCursor"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c4dc7c32-3f1a-47ed-bd25-232cb1409198"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5d23a3b9-6e0b-4cd9-b407-527bc23e67f5"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1e714573-aecc-462b-aadb-20d823f01cfe"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""49b06886-7147-4630-aab0-8e64b4ba8ade"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""moveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""45f670d5-7e8f-4348-8ac2-43cd0aa040bc"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a90cab4d-b8a1-4fa2-ac42-dd1f21a522e5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""leftMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec80f52f-824d-4548-9f09-3b84739905fb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5702f06e-6a58-40cf-882a-e76eb864e49c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""rightMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9730bd0d-13d2-4f42-81da-5acf0a8627ce"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""middleMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b9d6a64-0f14-40ca-b31f-2b77223d9a14"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""middleMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b78f836f-699f-4f02-8cfb-db5e94b32a8b"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""882359fd-aded-48c9-b7e6-5ab681e4f10e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""scroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c3bc550b-2532-446c-8964-9c67fff825f8"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0e6a1c49-bc2b-4022-9c6b-0d8b6b84fec2"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""515db75c-93b1-4eb6-8d1b-3e99b1c5a377"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""toogleMouseVisibility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // bullet_hell
        m_bullet_hell = asset.FindActionMap("bullet_hell", throwIfNotFound: true);
        m_bullet_hell_move_rigth = m_bullet_hell.FindAction("move_rigth", throwIfNotFound: true);
        m_bullet_hell_move_left = m_bullet_hell.FindAction("move_left", throwIfNotFound: true);
        m_bullet_hell_move_up = m_bullet_hell.FindAction("move_up", throwIfNotFound: true);
        m_bullet_hell_move_down = m_bullet_hell.FindAction("move_down", throwIfNotFound: true);
        m_bullet_hell_pause_menu = m_bullet_hell.FindAction("pause_menu", throwIfNotFound: true);
        m_bullet_hell_shoot = m_bullet_hell.FindAction("shoot", throwIfNotFound: true);
        m_bullet_hell_doge = m_bullet_hell.FindAction("doge", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Navigate = m_UI.FindAction("Navigate", throwIfNotFound: true);
        m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
        m_UI_Cancel = m_UI.FindAction("Cancel", throwIfNotFound: true);
        m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
        m_UI_Click = m_UI.FindAction("Click", throwIfNotFound: true);
        m_UI_ScrollWheel = m_UI.FindAction("ScrollWheel", throwIfNotFound: true);
        m_UI_MiddleClick = m_UI.FindAction("MiddleClick", throwIfNotFound: true);
        m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
        m_UI_TrackedDevicePosition = m_UI.FindAction("TrackedDevicePosition", throwIfNotFound: true);
        m_UI_TrackedDeviceOrientation = m_UI.FindAction("TrackedDeviceOrientation", throwIfNotFound: true);
        // VirtualMouse
        m_VirtualMouse = asset.FindActionMap("VirtualMouse", throwIfNotFound: true);
        m_VirtualMouse_point = m_VirtualMouse.FindAction("point", throwIfNotFound: true);
        m_VirtualMouse_moveCursor = m_VirtualMouse.FindAction("moveCursor", throwIfNotFound: true);
        m_VirtualMouse_leftMouseButton = m_VirtualMouse.FindAction("leftMouseButton", throwIfNotFound: true);
        m_VirtualMouse_rightMouseButton = m_VirtualMouse.FindAction("rightMouseButton", throwIfNotFound: true);
        m_VirtualMouse_middleMouseButton = m_VirtualMouse.FindAction("middleMouseButton", throwIfNotFound: true);
        m_VirtualMouse_scroll = m_VirtualMouse.FindAction("scroll", throwIfNotFound: true);
        m_VirtualMouse_toogleMouseVisibility = m_VirtualMouse.FindAction("toogleMouseVisibility", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // bullet_hell
    private readonly InputActionMap m_bullet_hell;
    private IBullet_hellActions m_Bullet_hellActionsCallbackInterface;
    private readonly InputAction m_bullet_hell_move_rigth;
    private readonly InputAction m_bullet_hell_move_left;
    private readonly InputAction m_bullet_hell_move_up;
    private readonly InputAction m_bullet_hell_move_down;
    private readonly InputAction m_bullet_hell_pause_menu;
    private readonly InputAction m_bullet_hell_shoot;
    private readonly InputAction m_bullet_hell_doge;
    public struct Bullet_hellActions
    {
        private @Controlls m_Wrapper;
        public Bullet_hellActions(@Controlls wrapper) { m_Wrapper = wrapper; }
        public InputAction @move_rigth => m_Wrapper.m_bullet_hell_move_rigth;
        public InputAction @move_left => m_Wrapper.m_bullet_hell_move_left;
        public InputAction @move_up => m_Wrapper.m_bullet_hell_move_up;
        public InputAction @move_down => m_Wrapper.m_bullet_hell_move_down;
        public InputAction @pause_menu => m_Wrapper.m_bullet_hell_pause_menu;
        public InputAction @shoot => m_Wrapper.m_bullet_hell_shoot;
        public InputAction @doge => m_Wrapper.m_bullet_hell_doge;
        public InputActionMap Get() { return m_Wrapper.m_bullet_hell; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Bullet_hellActions set) { return set.Get(); }
        public void SetCallbacks(IBullet_hellActions instance)
        {
            if (m_Wrapper.m_Bullet_hellActionsCallbackInterface != null)
            {
                @move_rigth.started -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnMove_rigth;
                @move_rigth.performed -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnMove_rigth;
                @move_rigth.canceled -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnMove_rigth;
                @move_left.started -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnMove_left;
                @move_left.performed -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnMove_left;
                @move_left.canceled -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnMove_left;
                @move_up.started -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnMove_up;
                @move_up.performed -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnMove_up;
                @move_up.canceled -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnMove_up;
                @move_down.started -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnMove_down;
                @move_down.performed -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnMove_down;
                @move_down.canceled -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnMove_down;
                @pause_menu.started -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnPause_menu;
                @pause_menu.performed -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnPause_menu;
                @pause_menu.canceled -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnPause_menu;
                @shoot.started -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnShoot;
                @shoot.performed -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnShoot;
                @shoot.canceled -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnShoot;
                @doge.started -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnDoge;
                @doge.performed -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnDoge;
                @doge.canceled -= m_Wrapper.m_Bullet_hellActionsCallbackInterface.OnDoge;
            }
            m_Wrapper.m_Bullet_hellActionsCallbackInterface = instance;
            if (instance != null)
            {
                @move_rigth.started += instance.OnMove_rigth;
                @move_rigth.performed += instance.OnMove_rigth;
                @move_rigth.canceled += instance.OnMove_rigth;
                @move_left.started += instance.OnMove_left;
                @move_left.performed += instance.OnMove_left;
                @move_left.canceled += instance.OnMove_left;
                @move_up.started += instance.OnMove_up;
                @move_up.performed += instance.OnMove_up;
                @move_up.canceled += instance.OnMove_up;
                @move_down.started += instance.OnMove_down;
                @move_down.performed += instance.OnMove_down;
                @move_down.canceled += instance.OnMove_down;
                @pause_menu.started += instance.OnPause_menu;
                @pause_menu.performed += instance.OnPause_menu;
                @pause_menu.canceled += instance.OnPause_menu;
                @shoot.started += instance.OnShoot;
                @shoot.performed += instance.OnShoot;
                @shoot.canceled += instance.OnShoot;
                @doge.started += instance.OnDoge;
                @doge.performed += instance.OnDoge;
                @doge.canceled += instance.OnDoge;
            }
        }
    }
    public Bullet_hellActions @bullet_hell => new Bullet_hellActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Navigate;
    private readonly InputAction m_UI_Submit;
    private readonly InputAction m_UI_Cancel;
    private readonly InputAction m_UI_Point;
    private readonly InputAction m_UI_Click;
    private readonly InputAction m_UI_ScrollWheel;
    private readonly InputAction m_UI_MiddleClick;
    private readonly InputAction m_UI_RightClick;
    private readonly InputAction m_UI_TrackedDevicePosition;
    private readonly InputAction m_UI_TrackedDeviceOrientation;
    public struct UIActions
    {
        private @Controlls m_Wrapper;
        public UIActions(@Controlls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_UI_Navigate;
        public InputAction @Submit => m_Wrapper.m_UI_Submit;
        public InputAction @Cancel => m_Wrapper.m_UI_Cancel;
        public InputAction @Point => m_Wrapper.m_UI_Point;
        public InputAction @Click => m_Wrapper.m_UI_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_UI_ScrollWheel;
        public InputAction @MiddleClick => m_Wrapper.m_UI_MiddleClick;
        public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
        public InputAction @TrackedDevicePosition => m_Wrapper.m_UI_TrackedDevicePosition;
        public InputAction @TrackedDeviceOrientation => m_Wrapper.m_UI_TrackedDeviceOrientation;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Navigate.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Submit.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Cancel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Point.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Click.started -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @ScrollWheel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @MiddleClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @RightClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @TrackedDevicePosition.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDevicePosition.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDevicePosition.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDevicePosition;
                @TrackedDeviceOrientation.started -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnTrackedDeviceOrientation;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @TrackedDevicePosition.started += instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.performed += instance.OnTrackedDevicePosition;
                @TrackedDevicePosition.canceled += instance.OnTrackedDevicePosition;
                @TrackedDeviceOrientation.started += instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.performed += instance.OnTrackedDeviceOrientation;
                @TrackedDeviceOrientation.canceled += instance.OnTrackedDeviceOrientation;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // VirtualMouse
    private readonly InputActionMap m_VirtualMouse;
    private IVirtualMouseActions m_VirtualMouseActionsCallbackInterface;
    private readonly InputAction m_VirtualMouse_point;
    private readonly InputAction m_VirtualMouse_moveCursor;
    private readonly InputAction m_VirtualMouse_leftMouseButton;
    private readonly InputAction m_VirtualMouse_rightMouseButton;
    private readonly InputAction m_VirtualMouse_middleMouseButton;
    private readonly InputAction m_VirtualMouse_scroll;
    private readonly InputAction m_VirtualMouse_toogleMouseVisibility;
    public struct VirtualMouseActions
    {
        private @Controlls m_Wrapper;
        public VirtualMouseActions(@Controlls wrapper) { m_Wrapper = wrapper; }
        public InputAction @point => m_Wrapper.m_VirtualMouse_point;
        public InputAction @moveCursor => m_Wrapper.m_VirtualMouse_moveCursor;
        public InputAction @leftMouseButton => m_Wrapper.m_VirtualMouse_leftMouseButton;
        public InputAction @rightMouseButton => m_Wrapper.m_VirtualMouse_rightMouseButton;
        public InputAction @middleMouseButton => m_Wrapper.m_VirtualMouse_middleMouseButton;
        public InputAction @scroll => m_Wrapper.m_VirtualMouse_scroll;
        public InputAction @toogleMouseVisibility => m_Wrapper.m_VirtualMouse_toogleMouseVisibility;
        public InputActionMap Get() { return m_Wrapper.m_VirtualMouse; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VirtualMouseActions set) { return set.Get(); }
        public void SetCallbacks(IVirtualMouseActions instance)
        {
            if (m_Wrapper.m_VirtualMouseActionsCallbackInterface != null)
            {
                @point.started -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnPoint;
                @point.performed -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnPoint;
                @point.canceled -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnPoint;
                @moveCursor.started -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnMoveCursor;
                @moveCursor.performed -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnMoveCursor;
                @moveCursor.canceled -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnMoveCursor;
                @leftMouseButton.started -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnLeftMouseButton;
                @leftMouseButton.performed -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnLeftMouseButton;
                @leftMouseButton.canceled -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnLeftMouseButton;
                @rightMouseButton.started -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnRightMouseButton;
                @rightMouseButton.performed -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnRightMouseButton;
                @rightMouseButton.canceled -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnRightMouseButton;
                @middleMouseButton.started -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnMiddleMouseButton;
                @middleMouseButton.performed -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnMiddleMouseButton;
                @middleMouseButton.canceled -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnMiddleMouseButton;
                @scroll.started -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnScroll;
                @scroll.performed -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnScroll;
                @scroll.canceled -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnScroll;
                @toogleMouseVisibility.started -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnToogleMouseVisibility;
                @toogleMouseVisibility.performed -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnToogleMouseVisibility;
                @toogleMouseVisibility.canceled -= m_Wrapper.m_VirtualMouseActionsCallbackInterface.OnToogleMouseVisibility;
            }
            m_Wrapper.m_VirtualMouseActionsCallbackInterface = instance;
            if (instance != null)
            {
                @point.started += instance.OnPoint;
                @point.performed += instance.OnPoint;
                @point.canceled += instance.OnPoint;
                @moveCursor.started += instance.OnMoveCursor;
                @moveCursor.performed += instance.OnMoveCursor;
                @moveCursor.canceled += instance.OnMoveCursor;
                @leftMouseButton.started += instance.OnLeftMouseButton;
                @leftMouseButton.performed += instance.OnLeftMouseButton;
                @leftMouseButton.canceled += instance.OnLeftMouseButton;
                @rightMouseButton.started += instance.OnRightMouseButton;
                @rightMouseButton.performed += instance.OnRightMouseButton;
                @rightMouseButton.canceled += instance.OnRightMouseButton;
                @middleMouseButton.started += instance.OnMiddleMouseButton;
                @middleMouseButton.performed += instance.OnMiddleMouseButton;
                @middleMouseButton.canceled += instance.OnMiddleMouseButton;
                @scroll.started += instance.OnScroll;
                @scroll.performed += instance.OnScroll;
                @scroll.canceled += instance.OnScroll;
                @toogleMouseVisibility.started += instance.OnToogleMouseVisibility;
                @toogleMouseVisibility.performed += instance.OnToogleMouseVisibility;
                @toogleMouseVisibility.canceled += instance.OnToogleMouseVisibility;
            }
        }
    }
    public VirtualMouseActions @VirtualMouse => new VirtualMouseActions(this);
    public interface IBullet_hellActions
    {
        void OnMove_rigth(InputAction.CallbackContext context);
        void OnMove_left(InputAction.CallbackContext context);
        void OnMove_up(InputAction.CallbackContext context);
        void OnMove_down(InputAction.CallbackContext context);
        void OnPause_menu(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnDoge(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnTrackedDevicePosition(InputAction.CallbackContext context);
        void OnTrackedDeviceOrientation(InputAction.CallbackContext context);
    }
    public interface IVirtualMouseActions
    {
        void OnPoint(InputAction.CallbackContext context);
        void OnMoveCursor(InputAction.CallbackContext context);
        void OnLeftMouseButton(InputAction.CallbackContext context);
        void OnRightMouseButton(InputAction.CallbackContext context);
        void OnMiddleMouseButton(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
        void OnToogleMouseVisibility(InputAction.CallbackContext context);
    }
}
